package bee

type ServiceGroup struct {
	BeeUserMapperService
	BeeShopGoodsCategoryService
	BeeShopInfoService
	BeeUserBalanceLogService
	BeeCouponService
	BeeUserCouponService
	BeeCashLogService
	BeeConfigService
	BeeShopGoodsPropService
	BeeShopGoodsAdditionService
	BeeShopGoodsService
	BeeShopGoodsImagesService
	BeeShopGoodsSkuService
	BeeShopGoodsContentService
	BeeWxConfigService
	BeeCommentService
	BeeOrderService
	BeeOrderReputationService
	BeeBannerService
	BeeUserAmountService
	BeeCyTableService
	BeeRegionService
	BeeCmsInfoService
	BeeUserAddressService
	BeePeiSongService
	BeeUserService
	BeeOrderGoodsService
	BeeOrderLogisticsService
	BeeUploadFileService
	BeePayLogService
	BeeWxPayConfigService
	BeeNoticeService
	BeeLogisticsService
	BeeOrderLogService
	BeePrinterService
}
